apiVersion: v1
kind: Service
metadata:
  name: my-ui-service
  labels:
    run: my-ui-service
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    run: my-ui-service
